[package]
name = "multihash_test"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
rs_merkle = "1.4.2"
serde = { version = "1.0.202", features = ["derive"] }
sha2 = "0.10.8"
sha256 = "1.5.0"
